config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tasks
      end
    end
  end

  resources :projects do
    resources :tasks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :tasks, -> { order(urgent: :desc, created_at: :desc, complete: :asc) }, dependent: :destroy
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :project

  scope :urgent, -> { where(urgent: true) }
  scope :non_urgent, -> { where(urgent: false) }
  scope :open_tasks, -> { where(complete: false) }
  scope :closed_tasks, -> { where(complete: true) }

  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < ApplicationController
  before_action :find_project, except: [:index, :create]

  def index
    @projects = Project.all
    render json: @projects
  end

  def create
    @project = Project.create!(project_params)
    render json: @project, status: :created

  def show
    render json: @project
  end

  def update
    @project.update(project_params)
    head :no_content
  end

  def destroy
    @project.destroy
    head :no_content
  end

  private

  def project_params
    params.require(:project).permit([:name])
  end

  def find_project
    @project ||= Project.find(params[:id])
  end
end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < ApplicationController
  before_action :find_project
  before_action :find_task, only: [:show, :update, :destroy]

  def index
    @tasks = @project.tasks
    render json: @tasks
  end

  def create
    task = @project.tasks.create(task_params)

    render json: task, status: :created
  end

  def show
    render json: @task
  end

  def update
    @task.update_attributes!(task_params)
    head :no_content
  end

  def destroy
    @task.destroy
    head :no_content
  end

  private

  def find_project
    @project ||= Project.find(params[:project_id])
  end

  def find_task
    @task = @project.tasks.find_by(id: params[:id]) if @project
  end

  def task_params
    params.require(:task).permit(:title, :description, :urgent, :deadline_at, :complete)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, except: [:index, :create, :new]

  def index
    @projects = Project.all
  end

  def create
    @project = Project.create!(project_params)
    redirect_to project_path(@project.id)
  end

  def new; end

  def show
    @tasks = @project.tasks
  end

  def edit; end

  def update
    @project.update(project_params)

    redirect_to project_path(@project.id)
  end

  def destroy
    @project.destroy

    redirect_to projects_path
  end

  private

  def project_params
    params.permit([:name])
  end

  def find_project
    @project ||= Project.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_project
  before_action :find_task, only: [:show, :update, :destroy]

  def index
    @tasks = @project.tasks
  end

  def create
    task = @project.tasks.create(task_params)
    redirect_to project_path(@project.id)
  end

  def show; end
  def new; end

  def update
    @task.update_attributes!(task_params)
    redirect_to project_path(@project.id)
  end

  def destroy
    @task.destroy
    redirect_to project_path(@project.id)
  end

  private

  def find_project
    @project ||= Project.find(params[:project_id])
  end

  def find_task
    @task = @project.tasks.find_by(id: params[:id]) if @project
  end

  def task_params
    params.permit(:title, :description, :urgent, :deadline_at, :complete)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      
      <%= yield %>
  </body>
</html>

app/views/projects/index.html.haml
%h1 Projects

- @projects.each do |project|
  %p= link_to "#{project.name} (#{project.tasks.open_tasks.count})", project_path(project.id) 

app/views/projects/new.html.haml
%h1 Create a New Project

= form_tag projects_path, method: :post, class: 'justify-content-center' do
  %p= text_field_tag :name, nil, class: 'form-control', required: true, title: 'Project Name', placeholder: 'Project Name'
  %p= button_tag 'Create Task', value: 'create_task', class: 'btn btn-primary'

          

app/views/projects/show.html.haml
%h1= "#{@project.name}"

%p= link_to "Add Task", new_project_task_path(@project.id) 
= form_tag project_path(@project.id), method: :put, class: 'justify-content-center' do
  %p= text_field_tag :name, @project.name, class: 'form-control', required: true, title: 'Project Name', placeholder: 'Project Name'
  %p= button_tag 'Update Project Name', value: 'update_project', class: 'btn btn-primary'

- if @tasks.urgent.open_tasks.count > 0
  %h3{class: 'text-secondary my-1'}  Urgent Tasks

  %div{class: 'my-2 border border-secondary rounded'}
    %div{class: 'row border-bottom border-secondary'}
      %div{class: 'col-sm ml-2'}
        Title
      %div{class: 'col-sm ml-2'}
        Urgent
      %div{class: 'col-sm ml-2'}
        Deadline
      %div{class: 'col-sm ml-2'}

    - @tasks.urgent.open_tasks.each do |task|
      %div{class: 'row my-2'}
        %div{class: 'col-sm ml-2'}
          = link_to task.title, project_task_path(@project.id, task.id), class: 'text-danger'
        %div{class: 'col-sm ml-2'}
          = task.urgent.to_s.titleize
        %div{class: 'col-sm ml-2'}
          = local_time(task.deadline_at) if task.deadline_at
        %div{class: 'col-sm ml-2'}
          = button_to 'Delete Task', project_task_path(@project.id, task.id), method: :delete, class: 'btn btn-danger'

- if @tasks.non_urgent.open_tasks.count > 0
  %h3{class: 'text-secondary my-1'} Backlog Tasks

  %div{class: 'my-2 border border-secondary rounded'}
    %div{class: 'row border-bottom border-secondary'}
      %div{class: 'col-sm ml-2'}
        Title
      %div{class: 'col-sm ml-2'}
        Urgent
      %div{class: 'col-sm ml-2'}
        Deadline
      %div{class: 'col-sm ml-2'}

    - @tasks.non_urgent.open_tasks.each do |task|
      %div{class: 'row my-2'}
        %div{class: 'col-sm ml-2'}
          = link_to task.title, project_task_path(@project.id, task.id), class: 'text-warning'
        %div{class: 'col-sm ml-2'}
          = task.urgent.to_s.titleize
        %div{class: 'col-sm ml-2'}
          = local_time(task.deadline_at) if task.deadline_at
        %div{class: 'col-sm ml-2'}
          = button_to 'Delete Task', project_task_path(@project.id, task.id), method: :delete, class: 'btn btn-danger'

- if @project.tasks.closed_tasks.count > 0
  %h3{class: 'text-secondary my-1'}  Closed Tasks

  %div{class: 'my-2 border border-secondary rounded'}
    %div{class: 'row border-bottom border-secondary'}
      %div{class: 'col-sm ml-2'}
        Title
      %div{class: 'col-sm ml-2'}
      %div{class: 'col-sm ml-2'}
      %div{class: 'col-sm ml-2'}

    - @project.tasks.closed_tasks.each do |task|
      %div{class: 'row my-2'}
        %div{class: 'col-sm ml-2'}
          = link_to task.title, project_task_path(@project.id, task.id), class: 'text-success'
        %div{class: 'col-sm ml-2'}
        %div{class: 'col-sm ml-2'}
        %div{class: 'col-sm ml-2'}
          = button_to 'Delete Task', project_task_path(@project.id, task.id), method: :delete, class: 'btn btn-danger'

app/views/tasks/new.html.haml
%h1= "Create a New Task for #{@project.name}"

= form_tag project_tasks_path, method: :post, class: 'justify-content-center' do
  %div{class: 'form-group'}
    %p= text_field_tag :title, nil, class: 'form-control', required: true, title: 'Task Title', placeholder: 'Task Title'
    %p= text_area_tag :description, nil, class: 'form-control', required: true, title: 'Task Description', placeholder: 'Task Description'
  %div{class: 'form-check form-check-inline'}
    = hidden_field_tag :urgent, false
    = check_box_tag :urgent, true, class: 'form-check-input'
    = label :urgent, 'Urgent', class: 'form-check-label'
  %div{class: 'form-group'}
    = date_field_tag :deadline_at, title: 'Deadline Date'
    = label :deadline_at, 'Deadline'
  %p= button_tag 'Create Task', value: 'create_task', class: 'btn btn-primary'

app/views/tasks/show.html.haml
%h1= "#{@task.title} for #{@project.name}"
%p= link_to "Back To Project", project_path(@project.id)
%p= link_to "Add Task", new_project_task_path(@project.id)

= form_tag project_task_path(@project.id, @task.id), method: :put, class: 'justify-content-center' do
  %div{class: 'form-group'}
    %p= text_field_tag :title, @task.title, class: 'form-control', required: true, title: 'Task Title', placeholder: 'Task Title'
    %p= text_area_tag :description, @task.description, class: 'form-control', required: true, title: 'Task Description', placeholder: 'Task Description'
  %div{class: 'form-check form-check-inline mx-2'}
    = label :urgent, 'Urgent', class: 'form-check-label mx-2'
    = hidden_field_tag :urgent, false
    = check_box_tag :urgent, true, class: 'form-check-input mx-2'
  %div{class: 'form-check form-check-inline'}
    = label :complete, 'Complete', class: 'form-check-label mx-2'
    = hidden_field_tag :complete, false
    = check_box_tag :complete, true, class: 'form-check-input mx-2'
  %div{class: 'form-group'}
    = date_field_tag :deadline_at, @task.deadline_at, title: 'Deadline Date'
    = label :deadline_at, 'Deadline'
  %p= button_tag 'Update Task', value: 'update_task', class: 'btn btn-primary'
%p= button_to 'Delete Task', project_task_path(@task.project_id, @task.id), method: :delete, class: 'btn btn-danger'